print("          __________________")
print("         /                  \\")
print("        /                    \\")
print("       /      😎            \\")
print("      /                      \\")
print("     /________________________\\")
print("     |                        |")
print("     |      ANAK INFORMATIKA  |")
print("     |                        |")
print("     |       UNAND            |")
print("     |________________________|")
print("          ||          ||")
print("          ||          ||")
print("          ||          ||")
print("        __||__      __||__")
print("       /      \\    /      \\")
print("      /________\\  /________\\")